
# initProbe : container가 가장 먼저 시작하기전에 실행되는 Probe
# --> 실패시, container 재시작. 
# livelienessProbe : container가 살아있기 위한 Probe
# --> 실패시, container 재시작.
# readnessProbe : container가 준비되었는지 확인하는 Probe
# --> 실패시, pod의 IP주소를 Endpoint에서 제거 ( 서비스에서 접근 불가능 )

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: liveness-exec
  name: liveness-exec
spec:
  containers:
  - name: tardy-nginx 
    image: sysnet4admin/tardy-nginx 
    livenessProbe:
      exec:
        command:
        - cat 
        - /tmp/healthy-on
      initialDelaySeconds: 10
      periodSeconds: 10 #it cannot start properly 

# tardy-nginx라는 image가 올라오는데 30초 걸림. 
# initialDelaySeconds: 10 --> 10초후에 livenessProbe 실행
# 10초 후에도 image가 준비되어 있지 않기때문에 periodSecond 10초 후에 libelinessProbe 실행
# 그래도 준비가 안되어 있기때문에 컨테이너가 위와같은 과정을 계속 재시작하고 반복함. 

# readinessProbe는 실패해도, 컨테이너가 재시작되지 않고, 서비스에서 endpoints만 제거됨. 
# 그리고 periodSeconds마다 검증해서 성공하면 endpoints에 다시 추가됨. 
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: readiness-exec
  name: readiness-exec
spec:
  containers:
  - name: tardy-nginx 
    image: sysnet4admin/tardy-nginx 
    readinessProbe:
      exec:
        command:
        - cat 
        - /tmp/healthy-on
      initialDelaySeconds: 10
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: readiness-exec-lb
spec:
  selector:
    run: readiness-exec
  ports:
    - name: http
      port: 80
      targetPort: 80 
  type: LoadBalancer
# --> 처음 몇초간은 서비스에서 제외, 그 이후에 endpoints에 추가됨. 정상동작. 

# 대게, initProbe가 있는경우는, liveliness,readiness가 있는 경우가 대부분 (없다면 설계상 이상한게 아닐까?...)
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: startup-w-others
  name: startup-w-others
spec:
  containers:
  - name: tardy-nginx 
    image: sysnet4admin/tardy-nginx  
    startupProbe:
      exec:
        command:
        - cat 
        - /tmp/healthy-on
      initialDelaySeconds: 10
      periodSeconds: 60
    livenessProbe:
      exec:
        command:
        - cat 
        - /tmp/healthy-on
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
        - cat 
        - /tmp/healthy-on
      initialDelaySeconds: 5
      periodSeconds: 5