
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-always
  name: pod-always
spec:
  containers:
  - image: sysnet4admin/net-tools
    name: net-tools
    command: ["/bin/sh", "-c"]
    args:
    - nslookup kubernetes
  restartPolicy: Always 

# restartPolicy: Always / Never / ONFailure
# deployment resource는 restartPolicy: 무조건 Always로 설정되어있어야함. 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-onfailure-failure
  name: deploy-onfailure-failure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-onfailure-failure
  template:
    metadata:
      labels:
        app: deploy-onfailure-failure
    spec:
      containers:
      - name: nginx
        image: nginx
      restartPolicy: OnFailure  # --> error. 