apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-api
  labels:
    app: scraper-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-api
  template:
    metadata:
      labels:
        app: scraper-api
    spec:
      containers:
      - name: scraper-api
        image: hyeonghwan/mini-project-api:1.1
        volumeMounts:
        - name: nfs-vol
          mountPath: /api/dynamic-vol
      volumes:
      - name: nfs-vol
        nfs:
          server: 192.168.1.10
          path: /nfs_shared/dynamic-vol