apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-api
  labels:
    app: scraper-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper-api
  template:
    metadata:
      labels:
        app: scraper-api
    spec:
      containers:
      - name: scraper-api
        image: hyeonghwan/mini-project-api:latest
        volumeMounts:
        - name: nfs-provisioner
          mountPath: ./api
      volumes:
      - name: nfs-provisioner
        persistentVolumeClaim:
          claimName: task-pv-claim