
FROM python:3.9

RUN pip install --no-cache-dir fastapi uvicorn requests

RUN mkdir -p /api
# RUN mkdir -p /api/dynamic-vol
# RUN mkdir -p /api/dynamic-vol/html
# RUN mkdir -p /api/dynamic-vol/sentences
WORKDIR /api

# COPY ./api/app.py ./app.py
# COPY ./api/utils.py ./utils.py
# COPY html/ ./html
# COPY sentences/ ./sentences

EXPOSE 80

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "80"]