apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-preprocessor
  labels:
    app: text-preprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: text-preprocessor
  template:
    metadata:
      labels:
        app: text-preprocessor
    spec:
      containers:
      - name: text-preprocessor
        image: hyeonghwan/mini-project-text-preprocessor:latest
        volumeMounts:
        - name: nfs-provisioner
          mountPath: ./
      volumes:
      - name: nfs-provisioner
        persistentVolumeClaim:
          claimName: task-pv-claim
---