
# taint가 적용되어 있는 node는 pod를 배치할때, 
# toleration을 통해서 taint를 무시하고 배치할 수 있음.
# 적용 방법은
# --> kubectl taint nodes w3-k8s DB=customer-info:NoSchedule
# key: DB, value: customer-info, Effect: NoSchedule
# 제거 방법
# --> kubectl taint nodes w3-k8s DB:NoSchedule-

# taint가 적용되어 있는 node에 pode를 배치하는 방법. 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-w-tolerations
  name: deploy-w-tolerations
spec:
  replicas: 6
  selector:
    matchLabels:
      app: deploy-w-tolerations
  template:
    metadata:
      labels:
        app: deploy-w-tolerations
    spec:
      containers:
      - image: nginx
        name: nginx
      tolerations:
      - effect: NoSchedule
        key: DB
        value: customer-info

# 현재 node에 tain가 적용되어 있음 DB=cluster-info:NoSchedule
# 그리고 해당 pod는 toleration을 가지고 있음. 따라서 해당 노드에 scheduling됨. 
# if. NoSchedule이 아닌 PreferNoSchedule이면, 가급적 배치하되, 다른 node에 배치됨.
# if. NoExecute라면, 해당 node는 pod에 배치될 수 있고, 만약 해당 node에 배치된 pod중 해당 toleration이 없으면 종료시켜버림. 