
FROM python:3.9

RUN mkdir -p /api
RUN mkdir -p /api/html
RUN mkdir -p /api/sentences
WORKDIR /api

COPY text_preprocessor.py ./text_preprocessor.py
COPY utils.py ./utils.py
COPY html/ ./html
COPY sentences/ ./sentences

RUN pip install --no-cache-dir fastapi uvicorn requests bs4

EXPOSE 80

CMD ["sleep 20000"]